bugfix: add systemInstruction to README
googleapis/nodejs-vertexai pull request #386
Opened 2024-07-25 08:48 UTC by leezhengjing

This pull request aims to add an example systemInstruction parameter to the code snippet in README.

When I first used vertex AI for my personal project, I encountered a bug with the systemInstruction as I just typed systemInstruction: "My system instruction", and upon diving into the source code realized that it required an object of interface Content. Hope this helps developers when they see an example usage of systemInstruction in the README.

2024-08-02 17:25 UTC, yyyu-google requested changes
Thank you @leezhengjing for contributing to our repo. Your contribution will help many other users use this feature more easily.

Could you create a separate heading 2 called `System Instruction`?

Specifically, insert `## System Instruction` after Line 427, then put a code snippet to demonstrate this feature.

2024-08-03 01:59 UTC, leezhengjing commented
Thank you for reviewing my PR @yyyu-google ! I have added the changes requested, let me know if there's anything to change.

2024-08-03 21:55 UTC, yyyu-google approved these changes

2024-08-03 22:36 UTC, merged

2024-08-03 23:00 UTC, yyyu-google commented
Hi @leezhengjing 
I have merged your Pull Request. Just FYI, https://github.com/googleapis/nodejs-vertexai/commit/a824162a29b8c6ba3ccae46c492dd28e9c2baf9c should enable users to pass string as system instruction. If you update to the latest version (1.4.0 as per Aug 3 2024), you should be able to use string as system instruction.